# DOMAIN=example.com
# CONF_DIR=/etc/wireguard
# WEBUI_PORT=5000
# VPN_PORT=51820
---
# https://github.com/linuxserver/docker-wireguard
# https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/linuxserver.yml
# https://docs.techdox.nz/wireguard/
# https://www.youtube.com/watch?v=QLL5lT0SDoQ
# https://howto.novalagung.com/setup-wireguard-vpn-server
# https://github.com/ngoduykhanh/wireguard-ui/issues/479

services:
  wireguard:
    # https://hub.docker.com/r/linuxserver/wireguard/tags
    # https://hub.docker.com/r/ngoduykhanh/wireguard-ui/tags
    image: linuxserver/wireguard:1.0.20210914-r4-ls69
    container_name: wireguard-ui-wireguard
    # restart: unless-stopped # <- Managed by wireguard-ui
    hostname: wireguard-ui-wireguard.{{ DOMAIN }}
    networks:
      - nginx-proxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - VIRTUAL_HOST=wireguard-ui.{{ DOMAIN }}
      - VIRTUAL_PORT=5000
    env_file:
      - ./config.env
      - ./secret.env
      - ./static.env
    volumes:
      - '{{ CONF_DIR }}/wireguard:/config'
    ports:
      - '{{ VPN_PORT }}:51820/udp'
      - '{{ WEBUI_PORT }}:5000'
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:0.6.2
    container_name: wireguard-ui
    restart: unless-stopped
    # hostname: wireguard-ui.{{ DOMAIN }}
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    environment: []
    # https://github.com/compose-spec/compose-spec/blob/main/spec.md#network_mode
    network_mode: service:wireguard
    env_file:
      - ./config.env
      - ./secret.env
      - ./static.env
    volumes:
      - '{{ CONF_DIR }}/wireguard-ui/db:/app/db'
      - '{{ CONF_DIR }}/wireguard-ui/config:/etc/wireguard'

networks:
  nginx-proxy:
    external: true
