# DOMAIN=example.com
# CONF_DIR=/etc/vaultwarden
# WEBUI_PORT=80
---
services:
  vaultwarden:
    # https://hub.docker.com/r/vaultwarden/server/tags
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    restart: unless-stopped
    hostname: vaultwarden.{{ DOMAIN }}
    networks:
      - nginx-proxy
    # template.env:
    #   https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
    environment:
      - VIRTUAL_HOST=vaultwarden.{{ DOMAIN }}
      - VIRTUAL_PORT=80
      # Required with a reverse proxy, vaultwarden needs to know it's https
      # to work properly with attachments
      - DOMAIN=https://vaultwarden.{{ DOMAIN }}
    env_file:
      - ./config.env
      - ./secret.env
      - ./static.env
    volumes:
      - '{{ CONF_DIR }}:/data'
    ports:
      - '{{ WEBUI_PORT }}:80'

networks:
  nginx-proxy:
    external: true
