# DOMAIN=example.com
# CONF_DIR=/etc/gotify
# WEBUI_PORT=80
# UID=0
# GID=0
---
services:
  gotify:
    # https://hub.docker.com/r/gotify/server/tags
    image: gotify/server:2.6.1
    container_name: gotify
    restart: unless-stopped
    hostname: gotify.{{ DOMAIN }}
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=gotify.{{ DOMAIN }}
      - VIRTUAL_PORT=80
    env_file:
      - ./config.env
    volumes:
      - '{{ CONF_DIR }}:/app/data'
    ports:
      - '{{ WEBUI_PORT }}:80'
    user: '{{ UID }}:{{ GID }}'

networks:
  nginx-proxy:
    external: true
