[init]
  defaultBranch = {{ DEFAULT_BRANCH }}
[user]
  name = {{ USER }}
  email = {{ EMAIL }}
[alias]
  co = commit
  ch = checkout
  rb = rebase
  ls = log --oneline -10
  ll = log --oneline
  lg = log --oneline --graph --decorate --abbrev-commit
  stat = status -u
  dif = diff --color-words
[push]
  default = simple
[pull]
  ff = only
[core]
  editor = {{ EDITOR }}
  # editor = mcedit
[diff]
  tool = {{ DIFF_TOOL }}
  # tool = mcdiff
[merge]
  tool = {{ MERGE_TOOL }}
[mergetool]
  keepBackup = false
[difftool "{{ DIFF_TOOL }}"]
  cmd = vimdiff $LOCAL $REMOTE
[difftool "mcdiff"]
  cmd = mcdiff $LOCAL $REMOTE
