# DOMAIN=example.com
# HTTP_PORT=80
---
services:
  nginx-proxy:
    # https://hub.docker.com/r/jwilder/nginx-proxy/tags
    image: jwilder/nginx-proxy:1.7.0-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    hostname: nginx-proxy.{{ DOMAIN }}
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '{{ HTTP_PORT }}:80'

networks:
  nginx-proxy:
    external: true
