# DOMAIN=example.com
# CONF_DIR=/etc/heimdall
# WEBUI_PORT=80
---
services:
  heimdall:
    # https://hub.docker.com/r/linuxserver/heimdall/tags
    image: linuxserver/heimdall:2.6.3
    container_name: heimdall
    restart: unless-stopped
    hostname: heimdall.{{ DOMAIN }}
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=heimdall.{{ DOMAIN }}
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
    env_file:
      - ./config.env
    volumes:
      - '{{ CONF_DIR }}:/config'
      - ./fix-https.sh:/scripts/fix-https.sh:ro
    ports:
      - '{{ WEBUI_PORT }}:80'
      # - 443:443
    post_start:
      # Use with reverse proxy
      - command: /bin/bash /scripts/fix-https.sh

networks:
  nginx-proxy:
    external: true
