# DOMAIN=example.com
# CONF_DIR=/etc/adguard
# WEBUI_PORT=80
# INITUI_PORT=3000
---
services:
  adguard:
    # https://hub.docker.com/r/adguard/adguardhome/tags
    image: adguard/adguardhome:v0.107.56
    container_name: adguard
    restart: unless-stopped
    # hostname: adguard.{{ DOMAIN }}
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=adguard.{{ DOMAIN }}
      - VIRTUAL_PORT=80
    env_file:
      - ./config.env
    volumes:
      - '{{ CONF_DIR }}/conf:/opt/adguardhome/conf'
      - '{{ CONF_DIR }}/work:/opt/adguardhome/work'
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '{{ WEBUI_PORT }}:80/tcp'
      - '{{ INITUI_PORT }}:3000/tcp'
      # - '67:67/udp'
      # - '68:68/udp'
      # - '443:443/udp'
      # - '443:443/tcp'
      # - '853:853/udp'
      # - '853:853/tcp'
      # - '5443:5443/udp'
      # - '5443:5443/tcp'
      # - '6060:6060/tcp'

networks:
  nginx-proxy:
    external: true
